name: E2E Tests
on: [push]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --force

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0
